# Generated by Django 5.1.6 on 2025-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='priceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('pricedifferencedollar', models.FloatField()),
                ('pricedifferenceperecentage', models.FloatField()),
            ],
        ),
    ]
