# Generated by Django 5.1.6 on 2025-04-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markettracking', '0002_remove_priceinstance_pricedifferencedollar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinstance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
