# Generated by Django 5.1.6 on 2025-04-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markettracking', '0004_crypto_alter_priceinstance_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='description',
        ),
    ]
