# Generated by Django 5.1.6 on 2025-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markettracking', '0005_remove_crypto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinstance',
            name='volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
