# Generated by Django 5.1.6 on 2025-04-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markettracking', '0006_priceinstance_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
