# Generated by Django 5.1.6 on 2025-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markettracking', '0007_crypto_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
