# Generated by Django 5.1.6 on 2025-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markettracking', '0008_crypto_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='current_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
